cookie:
  expiry_days: 30
  key: some_signature_key
  name: some_cookie_name
credentials:
  usernames:
    charlie:
      email: ka175896@npc.com.tw
      logged_in: false
      name: charlie
      password: $2b$12$qrOSAxosHjt6RYwvEzEjSe4sSO46TEduBSsei8pUmKAkJ7XLxVLFK
    daniel:
      email: N000192234@npc.com.tw
      logged_in: false
      name: danielhua
      password: $2b$12$Pj0SRNZC1LmztcFpXX//t.6rxbAfEHWDQdp8QLWuwXGYOeO4Sh2b6
    n000191032:
      email: N000191032@npc.com.tw
      logged_in: false
      name: Valerie
      password: $2b$12$YI2bUomcAeBCYozCGk2gWe7hgMR70uA/j6tiAb/XXkJ4sFyM8r3ea
    shao:
      email: N000192076@npc.com.tw
      logged_in: false
      name: shao
      password: $2b$12$/5Sw31T6Xwr0DlDRARHAM.RsPm.9qmqNT0gyi23feKE6h5QT4lLT2
    zmado:
      email: N000161772@npc.com.tw
      logged_in: false
      name: Zmado
      password: $2b$12$v29sXGhvqPEILE3sqZD4ceHWT33F6n8SusEXYMqaPlEGsXOLNUbwC
pre-authorized:
  emails: [N000192533@npc.com.tw]
